# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('blog', '0006_auto_20160321_1527')]
    operations = []

    if settings.PINAX_BLOG_SCOPING_MODEL is not None:
        dependencies.append(
            migrations.swappable_dependency(settings.PINAX_BLOG_SCOPING_MODEL)
        )

        operations.append(
            migrations.AddField(
                model_name='post',
                name='scoped_for',
                field=models.ForeignKey(related_name='blog_posts', to=settings.PINAX_BLOG_SCOPING_MODEL)
            )
        )
