# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_images', '0001_initial'),
        ('blog', '0006_auto_20160321_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pinax_images.ImageSet'),
        ),
    ]
