# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160905_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pinax_images.ImageSet'),
        ),
    ]
