# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160905_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
