# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_images', '0001_initial'),
        ('blog', '0010_auto_20161223_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='pinax_images.ImageSet'),
        ),
    ]
