# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_set_default_imagesets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='pinax_images.ImageSet'),
        ),
    ]
