# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_drop_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
