# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_drop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tweet_text',
        ),
    ]
