# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_conditional_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='pinax_images.ImageSet'),
        ),
    ]
